apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    harvesterhci.io/cloud-init-template: user
  name: k3s
  namespace: default
data:
  cloudInit: |-
    ## template: jinja
    #cloud-config

    users:
    - name: jeroen
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: "$6$FwXqnOc8hOs0Z65p$ZoBsbamvwbew.ryHzIqW3yy0pUgCHCbhq6WqRWuHwclg66imPz4uGwX0SrgLm7kk6d3Ji/Na32pN8ktZrGPhx1"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDmt6+SsXzLoRptifmSKlyjq6grRf4Yb1f2g0Etn7PKUK0LLKO3qZmSEgDwhohALXU7ZhSMVttYgLCjtFd4kG/JEdJVkGSqppLekgpc/T3yG8K3sO78UBdWtnLVY/6MtIHC1GHsAikTuPIJfIqftIk1RZwLKfIIgkT3HQAl9Kzn45QCVj4RrOhekHmqlgePrasTe1HKFRjQ/cuM6cqHSaPNWHrgshlci5BVTS6hqjNxeW/Rb/X4vDcvs/5glRvd0M3ESr1Aii5fhATzHSCGUje2U91ztRDvXdZQNsxQGPP1oTVTRa0oxKutpZee5lMEUjwU6hzoAx3jxPehayFjWJh
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHkFvXkGD1yoUsEMijoNi3tb0MlB3CiuQVdvpFsOf7P+ jeroen@localhost.localdomain
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSE68VYUiwL5a8xcmv34RZ1OYnrEcRBe4NaeKpE/twU jeroen@hierynomus.com
      lock_passwd: false
      shell: /bin/bash
    - name: erin
      passwd: "$6$SalTsaLt$qzEfb8Z5QsG6iOUHXuUEdS5/0T5uej5nYNcYZQQf99dCdB7l8zVBYGBjw3D9TqnSR4NDNIWxEckOEtmIAUc6n."
      shell: /bin/bash
      groups: users
      lock_passwd: false
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrkMfTTDxPafXv+E1olBKCqu3ggaRGeitMaJ5iJHr588Bo2PcPY+xlM5iM1WITNBwUtdotxtIPVv25sijeEB4eCn4Sx/460FB9cbucGMUqZeeMZe++ibziT/5vyDQhIBwEpw3tm5qtd1rLJkdIbq6hyxbkH2lr8RKfEGA9CCCTFeX7CPHHsVx3KXoS2TDceVHEaMaNBSpT1wkUJ26WLnbjYIkeTI2tqWmS/zV2u8wE9hyWsKheXRL3P9Ams+n2t4UmjNb0Xs96hkjHbcl8Pa8dlrOOER9oINWblfbuJR28Q3vlPR/3yLC1JI9o/+Vq92aMRZiA2BMg+uC/vj18GnKwrSJQ1tEt4hnHxwTaMBjBhXuH6AJDL1LxwKMhP8iNHmke/VuIUcjtusRmpDGtVy/Jov506FAN9coWqg0DC7RojwvGaK8SSCHDV6XLZGXg5PuoyiagCRqGsp6Y5FUMtodNLEzvWe3yLS7gOLTEfoddZM9cn+u9jzQVgyqfjT9xUtc= erquill@Erins-MacBook-Pro-2.local

    packages:
    - curl
    - qemu-guest-agent
    - helm

    package_update: true

    write_files:
    - path: /etc/sysctl.d/99-disable-ipv6.conf
      permissions: '0644'
      content: |
        # Disable IPv6 on all interfaces
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
        net.ipv6.conf.lo.disable_ipv6 = 1
    - path: /etc/rancher/k3s/config.yaml
      content: |
        write-kubeconfig-mode: "0644"
        tls-san:
        - {{ ds.meta_data.local_hostname }}.${ domain_suffix }
    - path: /tmp/install_k3s.sh
      content: |
        #!/bin/bash
        curl -sfL https://get.k3s.io -o get-k3s.sh
        INSTALL_K3S_CHANNEL="v1.31.5+k3s1" INSTALL_K3S_EXEC="--disable=traefik" sh get-k3s.sh
      permissions: '0755'

    runcmd:
    - firewall-cmd --permanent --add-port=6443/tcp #apiserver
    - firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
    - firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
    - firewall-cmd --reload
    - sysctl -p /etc/sysctl.d/99-disable-ipv6.conf                 # Disable IPv6
    - sudo /tmp/install_k3s.sh
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
