apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    harvesterhci.io/cloud-init-template: user
  name: k3s
  namespace: default
data:
  cloudInit: |-
    ## template: jinja
    #cloud-config

    users:
    - name: jeroen
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: "$6$FwXqnOc8hOs0Z65p$ZoBsbamvwbew.ryHzIqW3yy0pUgCHCbhq6WqRWuHwclg66imPz4uGwX0SrgLm7kk6d3Ji/Na32pN8ktZrGPhx1"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDmt6+SsXzLoRptifmSKlyjq6grRf4Yb1f2g0Etn7PKUK0LLKO3qZmSEgDwhohALXU7ZhSMVttYgLCjtFd4kG/JEdJVkGSqppLekgpc/T3yG8K3sO78UBdWtnLVY/6MtIHC1GHsAikTuPIJfIqftIk1RZwLKfIIgkT3HQAl9Kzn45QCVj4RrOhekHmqlgePrasTe1HKFRjQ/cuM6cqHSaPNWHrgshlci5BVTS6hqjNxeW/Rb/X4vDcvs/5glRvd0M3ESr1Aii5fhATzHSCGUje2U91ztRDvXdZQNsxQGPP1oTVTRa0oxKutpZee5lMEUjwU6hzoAx3jxPehayFjWJh
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHkFvXkGD1yoUsEMijoNi3tb0MlB3CiuQVdvpFsOf7P+ jeroen@localhost.localdomain
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSE68VYUiwL5a8xcmv34RZ1OYnrEcRBe4NaeKpE/twU jeroen@hierynomus.com
      lock_passwd: false
      shell: /bin/bash

    packages:
    - curl
    - qemu-guest-agent
    - helm

    package_update: true

    write_files:
    - path: /etc/rancher/k3s/config.yaml
      content: |
        write-kubeconfig-mode: "0644"
        tls-san:
        - {{ ds.meta_data.local_hostname }}.lab.geeko.me
    - path: /tmp/install_k3s.sh
      content: |
        #!/bin/bash
        curl -sfL https://get.k3s.io -o get-k3s.sh
        INSTALL_K3S_CHANNEL="v1.31.5+k3s1" INSTALL_K3S_EXEC="--disable=traefik" sh get-k3s.sh
      permissions: '0755'

    runcmd:
    - firewall-cmd --permanent --add-port=6443/tcp #apiserver
    - firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 #pods
    - firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 #services
    - firewall-cmd --reload
    - sudo /tmp/install_k3s.sh
    - - systemctl
      - enable
      - '--now'
      - qemu-guest-agent.service
