apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: backbone-vlan
  annotations:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: UntaggedNetwork
    #  key: string
  labels:
    {}
    #  key: string
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"backbone","type":"bridge","bridge":"mgmt-br","promiscMode":true,"ipam":{}}